version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk21
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8084:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

    environment:
      - JAVA_OPTS=-Djava.awt.headless=true
    networks:
      - devops-network


volumes:
  jenkins_home:
  #jenkins-docker-certs:

networks:
  devops-network:
    driver: bridge